Module7 task1
htmlacademy-javascript/127168-keksobooking-26 pull request #5
Opened 2022-06-29 21:32 UTC by samoshk1n

Всё должно работать. Есть подозрение, что проверка данных сделана уж слишком "в лоб" и усложнена. Возможно есть какой-то другой способ, но я так и не придумал 🤷‍♂️

2022-06-30 08:42 UTC, o-bender requested changes

2022-06-30 08:42 UTC, o-bender commented on js/element-generator.js
> +    const imageTemplate = popupPhotos.querySelector('.popup__photo');
Ненадёжный ход, а если из шаблона разметки уберут этот элемент? Т.е. в изначальной разметке popup__photos будет пустым.
Тут надо либо template отдельный сделать, либо функцию которая этот элемент создаёт через js.

2022-06-30 08:42 UTC, o-bender commented on js/element-generator.js
> +    const imagesFragment = document.createDocumentFragment();
Что бы не возиться с фрагментом можно делать так:
```
const createElement = (item) => {
    const p = document.createElement('p');
    p.textContent = item;
}

parentElement.append(...[1,2,3,4,5].map(createElement))
```

2022-07-04 18:48 UTC, samoshk1n commented on js/element-generator.js
> +  const featuresList = cardElement.querySelectorAll('.popup__feature');
Поменял выдачу фич. Изначально воспользовался замороченным способом из урока 7.11-7.12 - "Нюансы заполнения шаблонов данными". Там исходили из того, что в разметке находится всё, всё это сверяется с доступными фичами на наличие и удаляется то, чего не было в доступном. Но конечно понимаю, что проще по твоему способу это сделать) Да и в реалиях, как ты описал, наверно так действительно правильнее

2022-07-05 09:42 UTC, o-bender approved these changes

2022-07-05 09:42 UTC, o-bender commented on js/element-generator.js
> +const createDescriptionListFragment = (descriptionTemplate, descriptionData) => {
Эта функция не понадобится. Если зайти на какой-нибудь сайт с бронированием чего угодно, то подробно ты всегда видишь только одну карточку товара. Так и тут все сразу рисовать не придётся.

2022-07-05 09:42 UTC, o-bender commented on js/element-generator.js
> +const createDescriptionListFragment = (descriptionTemplate, descriptionData) => {
Эту функцию и всё что после неё, я бы преобразовал в функцию showCard = (cardDescription) =>
И её уже вызывал бы в main.js вместе с createDescriptions =)
main.js это точка входа в приложение, начало и конец программы. И делать вот так `mapBlock.append(newDescriptions.firstChild);` не в main.js. На мой взгляд для этого нужны очень веские основания. Т.к. этот код выполнится один раз в случайный момент, без контроля с твоей стороны. И повторить или перехватить ошибку при его выполнении ты не сможешь. Да и протестировать это сложно будет. И эти проблемы без условия, что там возникнет какая-нибудь хитрая ошибка=)

2022-07-05 09:42 UTC, o-bender commented on js/util.js
> +  } else if (supportNum > 1 && supportNum < 5) {
Тут можно и без else, т.к. в if всегда есть return:
```
if (number > 10 && number < 20) {
    return `${word}${wordEndings[2]}`;
} 
if (supportNum > 1 && supportNum < 5) {...}
if (supportNum === 1) {...}
```

2022-07-05 09:42 UTC, o-bender commented on js/element-generator.js
> +const descriptions = createDescriptions();
Это всё же пусть живёт в main.js. В конце файла я подробней опишу почему так

2022-07-05 09:42 UTC, o-bender commented on js/element-generator.js
> +const FEATURE_CLASS_NAME = 'popup__feature';
Константу перенеси в самый верх файла сразу после импортов. А то критерий не зачтут)

2022-07-05 09:42 UTC, merged